--- # This is a sample playbook for defining the Ansible Playbook ansible-playbook httpd.yaml
- hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts:
  vars:
    username: myuser
    passcheck: yes
  tasks:
  - name: Install NGINX servers on ALL groups
    yum:
      name: nginx
      state: latest
    notify: startservice
  handlers:
    - name: startservice
      service:
        name: nginx
        state: restarted
